name: snt_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  dotted_border: ^2.0.0
  url_launcher: ^6.2.5
  flip_card: ^0.7.0
  image_picker: ^1.1.2
  flutter:
    sdk: flutter
  qr_flutter: ^4.1.0
  supabase_flutter: ^2.0.0
  flutter_svg: ^2.0.7
  intl: ^0.19.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/Assets/Fonts/
    - lib/Assets/Images/logo.png
    - lib/Assets/Images/_Instagram.png
    - lib/Assets/Images/Gmail.png
    - lib/Assets/Images/LinkedIn.png 
    - lib/Assets/Images/Send.png
    - lib/Assets/Images/backgroundQr.png
    - lib/Assets/Images/backgroundContact.png
    - lib/Assets/Images/backgroundS&TNumbers.png
    - lib/Assets/Data/
    - lib/Assets/Images/
    - lib/Assets/Icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: lib/Assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: lib/Assets/fonts/Poppins-Medium.ttf
          weight: 500
